// VUE/proyectoapivue/src/components/Departamentos/InsertarDepartamento.vue
<template>
    <div>
        <h1>Soy insertar</h1>
        <router-link class="nav-link" to="/crudservicios"><button type="button" class="btn btn-danger">Volver</button></router-link>
        <div class="row justify-content-center">
            <div class="col-8 text-center">
                <form v-on:submit.prevent="insertarDepartamento()">
                    <div class="form-control">
                        <label>Numero :  {{" "}}</label><br/>
                        <input type="text" v-model="departamento.numero"/>
                    </div>
                    <div class="form-control">
                        <label>Nombre : {{" "}} </label><br/>
                        <input type="text" v-model="departamento.nombre"/>
                    </div>
                    <div class="form-control">
                        <label>Localidas : {{" "}}</label><br/>
                        <input type="text" v-model="departamento.localidad"/>
                    </div><br/>
                    <button class="btn btn-success">Insertar</button>
                </form>
            </div>
        </div>
    </div>
</template>
<script>
import ServiceDepartamentos from './../../services/ServicioDepartamentos'

const service = new ServiceDepartamentos();

export default{
    name : "InsertarDepartamento",
    methods : {
        insertarDepartamento(){
            this.departamento.numero = parseInt(this.departamento.numero);
            service.insertarDepartamento(this.departamento).then(res => {
                console.log(res);
                // Volvemos a la tabla
                this.$router.push("/crudservicios");
            });
        }
    },
    data(){
        return{
            departamento : {
                numero : 0,
                nombre : "",
                localidad : ""
            },
            mensaje : ""
        }
    }
}
</script>

// React/recatservicios/src/components/Departamentos/InsertarDepartamento.js
import React, { Component } from "react";
import axios from "axios";
import Global from "../../Global";
import { Redirect } from "react-router";

export default class InsertarDepartamento extends Component {
  cajaNumero = React.createRef();
  cajaNombre = React.createRef();
  cajaLocalidad = React.createRef();

  state = {
    mensaje: "Insertado correctamente.",
    status: false,
  };

  insertarDepartamento = (e) => {
    e.preventDefault();

    var num = parseInt(this.cajaNumero.current.value);
    var nom = this.cajaNombre.current.value;
    var locali = this.cajaLocalidad.current.value;

    var departamento = {
      numero: num,
      nombre: nom,
      localidad: locali,
    };

    var request = "/webresources/departamentos/post";
    var url = Global.urlCrudDepartamentos + request;
    axios.post(url, departamento).then((res) => {
      this.setState({
        mensaje: "Departamento insertado",
        status: true,
      });
    });
  };

  render() {
    return (
      <div className="row justify-content-center">
        <form
          onSubmit={this.insertarDepartamento}
          className="col-4 p-5 my-5 rounded"
          style={{
            backgroundColor: "lightyellow",
            border: "3px solid darkorange",
          }}
        >
          <div className="form-group row mb-3">
            <label>Numero: </label>
            <input
              type="number"
              className="form-control"
              ref={this.cajaNumero}
            />
          </div>
          <div className="form-group row">
            <label>Nombre: </label>
            <input type="text" className="form-control" ref={this.cajaNombre} />
          </div>
          <div className="form-group row mb-3">
            <label>Localidad: </label>
            <input
              type="text"
              className="form-control"
              ref={this.cajaLocalidad}
            />
          </div>
          <button className="btn btn-info">Insertar</button>
        </form>
        {this.state.status == true && <Redirect to="/departamentos" />}
      </div>
    );
  }
}
