// VUE/proyectoapivue/src/components/Departamentos/ModificarDepartamento.vue
<template>
    <div>
        <h1>Soy Modificar</h1>
        <router-link class="btn btn-danger" to="/crudservicios">Volver</router-link>
        <div class="row justify-content-center">
            <div class="col-8 text-center" v-if="departamento">
                <form v-on:submit.prevent="modificarDepartamento()">
                    <div class="form-control">
                        <label>Numero :  {{" "}}</label><br/>
                        <input type="text" v-model="departamento.numero"/>
                    </div>
                    <div class="form-control">
                        <label>Nombre : {{" "}} </label><br/>
                        <input type="text" v-model="departamento.nombre"/>
                    </div>
                    <div class="form-control">
                        <label>Localidas : {{" "}}</label><br/>
                        <input type="text" v-model="departamento.localidad"/>
                    </div><br/>
                    <button class="btn btn-success">Modificar</button>
                </form>
            </div>
        </div>
    </div>
</template>
<script>
import ServiceDepartamentos from './../../services/ServicioDepartamentos.js'

const service = new ServiceDepartamentos();
export default{
    name : "ModificarDepartamento",
    data() {
        return {
            departamento  : null,
            id : 0
        }
    },
    methods : {
        modificarDepartamento(){
            this.departamento.numero = parseInt(this.departamento.numero);
            service.modificarDepartamento(this.departamento).then(res=>{
                console.log(res);
                this.$router.push("/crudservicios");
            });

        },
        buscarDepartamento(){
           service.buscarDepartamento(this.id).then(res => {
               this.departamento = res;
           });
        }
    },
    mounted(){
        this.id  = this.$route.params.iddepartamento;
        this.buscarDepartamento();
    }
}
</script>

// React/recatservicios/src/components/Departamentos/ModificarDepartamento.js
import React, { Component } from "react";
import Global from "../../Global";
import axios from "axios";
import { NavLink } from "react-router-dom";
import { Redirect } from "react-router";

export default class ModificarDepartamento extends Component {
  id = this.props.idDepartamento;

  cajaNumero = React.createRef();
  cajaNombre = React.createRef();
  cajaLocal = React.createRef();

  state = {
    departamento: {},
    status: false,
  };

  modificarDepartamento = (e) => {
    e.preventDefault();
    var request = "/webresources/departamentos/put";
    var url = Global.urlCrudDepartamentos + request;
    console.log(url);

    var nombre = this.cajaNombre.current.value;
    var num = parseInt(this.cajaNumero.current.value);
    var locali = this.cajaLocal.current.value;

    var departamento = {
      numero: num,
      nombre: nombre,
      localidad: locali,
    };

    axios.put(url, departamento).then((res) => {
      this.setState({
        status: true,
      });
    });

    //axios.put(url).then((res) => {});
  };

  buscarDepartamento = () => {
    var request = "/webresources/departamentos/" + this.id;
    var url = Global.urlCrudDepartamentos + request;
    console.log(url);
    axios.get(url).then((res) => {
      this.setState({
        departamento: res.data,
      });
    });
  };

  componentDidMount = () => {
    this.buscarDepartamento();
  };

  render() {
    return (
      <div>
        <h1>Modificar</h1>
        <form onSubmit={this.modificarDepartamento}>
          <label>ID: </label>
          <input
            type="number"
            ref={this.cajaNumero}
            defaultValue={this.state.departamento.numero}
            disabled
          />{" "}
          <br /> <br />
          <label>Nombre: </label>
          <input
            type="text"
            ref={this.cajaNombre}
            defaultValue={this.state.departamento.nombre}
          />{" "}
          <br /> <br />
          <label>Localidad: </label>
          <input
            type="text"
            ref={this.cajaLocal}
            defaultValue={this.state.departamento.localidad}
          />
          <br />
          <br />
          <button className="btn btn-info">Modificar Datos</button>{" "}
          <NavLink className="btn btn-info" to="/departamentos">
            Volver
          </NavLink>
        </form>
        {this.state.status == true && <Redirect to="/departamentos" />}
      </div>
    );
  }
}
