// React/reactclases/src/components/Comics/Comic.js
import { Component } from "react";

class Comic extends Component{

    seleccionFavorito = () =>{
        var seleccionado = this.props.comic;
        this.props.metodoPadre(seleccionado);
    }

    elimnarComic = () =>{
        var indice = this.props.index;
        console.log(indice);
        this.props.metodoEliminar(indice);
    }

    modificarComic = () =>{
        
    }

    render () {
        return (
            <div style={{backgroundColor:"#69D2E7"}}>
                <hr/>
                <button onClick={this.seleccionFavorito}>Favorito</button>
                <button onClick={this.elimnarComic}>Eliminar</button>
                <button>Modificar</button>
                <h1 style={{color:"Blue"}}>{this.props.comic.titulo}</h1>
                <h6 style={{color:"orange"}}>{this.props.comic.descripcion}</h6>
                <img src={this.props.comic.imagen}/>
            </div>

        );
    }
}
export default Comic;

// VUE/proyectovuefinal/src/components/Comic.vue
<template>
   <div>
       <h1>El comic es : {{comic.titulo}}</h1>
       <img :src="comic.imagen"/>
       <h2>{{comic.descripcion}}</h2>
       <button @click="comicFavorito">Favorito</button>
       <button @click="modificarComic" style="backgroundColor:blue;color:white">Modificar</button>
       <button @click="eliminarComic" style="backgroundColor:red;color:white">Eliminar</button>
   </div>
    
</template>
<script>
export default {
    name : "Comic",
    props : ["comic", "indice"],
    methods : {
        comicFavorito(){
            this.$emit("favorito", this.comic);
        },
        eliminarComic(){
            //console.log(this.indice);
            this.$emit("eliminar", this.indice);
        },
        modificarComic(){
            //console.log(this.indice);
            this.$emit("modificar", this.indice);
        }
    }
}
</script>

<style scoped>
    img{
        width : 325px;
    }
</style>
