// Angular/primerproyecto/src/components/tablamultiplicar/tablamultiplicar.component.ts
import { Component, ViewChild, ElementRef  } from "@angular/core";

@Component({
    selector : "app-tabla-multiplicar",
    templateUrl : "./tablamultiplicar.component.html"
})

export class TablaMultiplicar{
    @ViewChild("cajaNumero") cajaNumero : ElementRef;
    public num : number;
    public numros : Array<number>;

    constructor(){
        this.cajaNumero = new ElementRef(0);
        this.numros = new Array<number>();
        this.num = 0;
    }

    setNumero(){
        this.num = parseInt(this.cajaNumero.nativeElement.value);
        this.numros = [];
        for(var i = 0; i <= 10; i++){
            var opera = i * this.num;
            this.numros.push(opera);
        }
    }
}
<h1>Soy la tabla</h1>

<form #tabla="ngForm">
    <label>Numero</label>
    <input type="number" name="cajaNumero" #cajaNumero/>
    <button (click)="setNumero()">CALCULAR</button>
</form> <br/>

<ul>
    <li *ngFor="let nume of numros;let i = index">{{num}}x{{i}}={{nume}}</li>
</ul>

<table border="2">
    <tr>
        <td>Operación</td>
        <td>Resultado</td>
    </tr>
    <tr *ngFor="let nume of numros;let i = index">
        <td>{{num}}x{{i}}</td>
        <td>{{nume}}</td>
    </tr>
</table>

// VUE/proyectovuefinal/src/components/TablaMultiplicar.vue
<template>
  <div>
    <h1>Tabla de multiplicar de {{num}}</h1>
    <label>Introduzca un numero: </label>
    <input type="number" v-model="num" />
    <br />
    <button type="button" @click="calcularTabla()">
      Mostrar tabla de multiplicar
    </button>
    <hr />

    <table id="tabla" border="2">
      <thead>
        <tr>
            <th style="color:green">Operación</th>
            <th style="color:green">Resultado</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="i in solucion" :key="i" v-html="i">{{i}}</tr>
        <!-- <tr v-for="i in 10" :key="i">
            <td>{{ num }} x {{ i }}</td>
            <td>{{ num * i }}</td>
        </tr> -->
      </tbody>
    </table>
  </div>
</template>
<script>
export default {
  name: "TablaMultiplicar",
  data() {
    return {
      num: 0,
      solucion: [],
    };
  },
  methods: {
    calcularTabla() {
        //Se vacia el array antes de hacer nada
        this.solucion = [];
      // SOLO UN ARRAY :)
      for (var i = 0; i <= 10; i++) {
        var solu = parseInt(this.num) * i;
        var dibujo =
            "<td style='color:red'>" + this.num + "x" + i + "</td>" + "<td style='color:blue'>" + solu + "</td>";
        this.solucion.push(dibujo);
      }
      // ESTARIA GUAY UN RETURN
      return this.solucion;
    },
  },
};
</script>
