// VUE/practicavueseries/src/components/Series/TablaPersonajes.vue
<template>
    <div>
        <h1>Soy la tabla de personajes</h1>
        <router-link class="btn btn-primary" :to="'/detallesSerie/'+id">Volver</router-link><br/><br/>
        <div class="row justify-content-center">
            <div class="col-8 text-center">
                <table class="table table-striped" border="2">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Imagen</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(personaje,index) in personajes" :key="index">
                            <td>{{personaje.nombre}}</td>
                            <td><img :src="personaje.imagen"/></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</template>
<script>
import ServiceSeries from './../../services/Series';

const service = new ServiceSeries();

export default{
    name : "TablaPersonajes",
    data(){
        return {
           personajes : [],
           id : 0
        }
    },
    mounted(){
        this.id = this.$route.params.idSerie;
        this.cargarPersonajes();
    },
    methods : {
        cargarPersonajes(){
            service.getPersonajes(this.id).then(res => {
                this.personajes = res;
            });
        }
    }
}
</script>
<style scoped>
    img{
        width: 350px;
    }
</style>

// Angular/proyectoseriesangular/src/app/components/tablapersonajes/tablapersonajes.component.ts
import { Component, OnInit } from '@angular/core';
import { ServiceSeries } from 'src/app/services/series.service';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { Personajes } from 'src/app/model/Personajes';

@Component({
  selector: 'app-tablapersonajes',
  templateUrl: './tablapersonajes.component.html',
  styleUrls: ['./tablapersonajes.component.css']
})
export class TablapersonajesComponent implements OnInit {

  public idSerie! : string;
  public personajes! : Array<Personajes>;

  constructor(private _route :ActivatedRoute, private _service : ServiceSeries, private _router : Router) { }

  ngOnInit(): void {
    this._route.params.subscribe((params : Params) => {
      this.idSerie = params['idSerie'];
      console.log(this.idSerie);
      this.cargarTabla();
    });
  }

  cargarTabla(){
    this._service.getPersonajesSerieId(this.idSerie).subscribe(res => {
      this.personajes = res;
    });
  }

}

<div>
    <div>
        <a [routerLink]="['/detallesseries',idSerie]">Volver</a>
        <table>
            <thead>
                <tr>
                    <th>Nombre</th>
                    <td>Imagen</td>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let personaje of personajes">
                    <td>{{personaje.nombre}}</td>
                    <td><img width="150px" src="{{personaje.imagen}}" alt="img"/></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
