// VUE/practicavueseries/src/components/Series/DetallesSerie.vue
<template>
    <div>
        <h2>{{serie.nombre}}</h2>
        <img :src="serie.imagen"/>
        <h3>La puntuación es de : {{serie.puntuacion}}</h3>
        <h3>Es del año : {{serie.anyo}}</h3>
        <router-link class="btn btn-success" :to="'/tablaSeries/'+serie.idSerie">Personajes Series</router-link>
    </div>
</template>
<script>
import ServiceSeries from './../../services/Series';
const service = new ServiceSeries();
export default{
    name : "DetallesSerie",
    data ()  {
        return {
            id : 0,
            serie : {}
        }
    },
    mounted(){
        this.cargarSerie();
    },
    watch:{
        '$route.params.idSerie'(nextprop, prevprop){
            if(nextprop != prevprop){
                this.cargarSerie();
            }
        }
    },
    methods : {
        cargarSerie(){
            this.id = this.$route.params.idSerie;
            service.getSerie(this.id).then(res => {
                console.log(res);
                this.serie = res;
            });
        }
    }
}
</script>

<style scoped>
    img{
        width: 400px;
    }
</style>

// Angular/proyectoseriesangular/src/app/components/detallesserie/detallesserie.component.ts
import { Component, OnInit } from '@angular/core';
import { Series } from 'src/app/model/Series';
import { ServiceSeries } from 'src/app/services/series.service';
import { ActivatedRoute, Params, Router } from '@angular/router';

@Component({
  selector: 'app-detallesserie',
  templateUrl: './detallesserie.component.html',
  styleUrls: ['./detallesserie.component.css']
})
export class DetallesserieComponent implements OnInit {

  public serie! : Series;
  public idSerie! : number;

  constructor(private _route :ActivatedRoute, private _service : ServiceSeries, private _router : Router) { }

  ngOnInit(): void {
    this._route.params.subscribe((params : Params) => {
      var num = parseInt(params['idSerie']);
      this.idSerie = num;
      console.log(this.idSerie);
      this.buscarSerie();
    });
  }

  buscarSerie(){
    this._service.getSerieId(this.idSerie).subscribe(res => {
      this.serie = res;
    });
  }

}

<div *ngIf="serie">
    <div>
        <h1>{{serie.nombre}}</h1>
        <img width="200px" src="{{serie.imagen}}" alt="img"/>
        <h2>Puntuación : {{serie.puntuacion}}</h2>
        <h2>Año : {{serie.anyo}}</h2>
        <a [routerLink]="['/tablapersonajes',serie.idSerie]">Cargar Personajes</a>
    </div>
</div>
