// VUE/proyectoapivue/src/components/Departamentos/InsertarDepartamento.vue
<template>
    <div>
        <h1>Soy insertar</h1>
        <router-link class="nav-link" to="/crudservicios"><button type="button" class="btn btn-danger">Volver</button></router-link>
        <div class="row justify-content-center">
            <div class="col-8 text-center">
                <form v-on:submit.prevent="insertarDepartamento()">
                    <div class="form-control">
                        <label>Numero :  {{" "}}</label><br/>
                        <input type="text" v-model="departamento.numero"/>
                    </div>
                    <div class="form-control">
                        <label>Nombre : {{" "}} </label><br/>
                        <input type="text" v-model="departamento.nombre"/>
                    </div>
                    <div class="form-control">
                        <label>Localidas : {{" "}}</label><br/>
                        <input type="text" v-model="departamento.localidad"/>
                    </div><br/>
                    <button class="btn btn-success">Insertar</button>
                </form>
            </div>
        </div>
    </div>
</template>
<script>
import ServiceDepartamentos from './../../services/ServicioDepartamentos'

const service = new ServiceDepartamentos();

export default{
    name : "InsertarDepartamento",
    methods : {
        insertarDepartamento(){
            this.departamento.numero = parseInt(this.departamento.numero);
            service.insertarDepartamento(this.departamento).then(res => {
                console.log(res);
                // Volvemos a la tabla
                this.$router.push("/crudservicios");
            });
        }
    },
    data(){
        return{
            departamento : {
                numero : 0,
                nombre : "",
                localidad : ""
            },
            mensaje : ""
        }
    }
}
</script>

// Angular/angularcruddepartamento/src/app/components/insertardepartamento/insertardepartamento.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ServiceDepartamentos } from 'src/app/services/departamentos.service';
import { Router } from '@angular/router';
import { Departamento } from 'src/app/model/Departamento';

@Component({
  selector: 'app-insertardepartamento',
  templateUrl: './insertardepartamento.component.html',
  styleUrls: ['./insertardepartamento.component.css']
})
export class InsertardepartamentoComponent implements OnInit {

  @ViewChild("cajaNumero") cajaNumero! : ElementRef;
  @ViewChild("cajaNombre") cajaNombre! : ElementRef;
  @ViewChild("cajaLocalidad") cajaLocalidad! : ElementRef;

  constructor(private _service: ServiceDepartamentos, private _router : Router) { }

  ngOnInit(): void {
  }

  insertarDepartamento():void{
    var numero = parseInt(this.cajaNumero.nativeElement.value);
    var nombre = this.cajaNombre.nativeElement.value;
    var localidad = this.cajaLocalidad.nativeElement.value;

    var departamento = new Departamento(numero,nombre,localidad);

    this._service.insertDepartamento(departamento).subscribe(res=>{
      this._router.navigate(['/home']);
    });
  }

}

<div class="row justify-content-center">
    <div class="col-8 text-center">
        <h1>Nuevo Departamento</h1>
        <form #formDepartamento="ngForm">
            <label>Numero: </label>
            <input type="number" name="cajaNumero" #cajaNumero/><br/>
            <label>Nombre: </label>
            <input type="text" name="cajaNombre" #cajaNombre/><br/>
            <label>Localidad: </label>
            <input type="text" name="cajaLocalidad" #cajaLocalidad/><br/>
            <button (click)="insertarDepartamento()">Insertar</button>
        </form>
    </div>
</div>
